#!/bin/bash
# vim: autoindent tabstop=4 shiftwidth=4 expandtab softtabstop=4 filetype=bash
# -*- mode: sh; indent-tabs-mode: nil; sh-basic-offset: 4 -*-
exec >oslat-client-stderrout.txt
exec 2>&1

. /usr/bin/oslat-base || (echo "/usr/bin/oslat-base not found"; exit 1)

dump_runtime
validate_label
validate_sw_prereqs

if [ -z "${WORKLOAD_CPUS}" ]; then
    exit_error "WORKLOAD_CPUS is not defined.  This must be defined to run oslat"
else
    echo "WORKLOAD_CPUS: ${WORKLOAD_CPUS}"
fi
if [ -z "${HK_CPUS}" ]; then
    exit_error "HK_CPUS is not defined.  This must be defined to run oslat"
else
    echo "HK_CPUS: ${HK_CPUS}"
fi

no_load_balance=0
rtprio_opt=""
duration=60
smt="on"

opts=$(getopt -q -o "" --longoptions "no-load-balance:,rtprio:,duration:,smt:" -n "getopt.sh" -- "$@");
if [ $? -ne 0 ]; then
    printf -- "\tUnrecognized option specified\n\n"
    exit 1
fi
eval set -- "$opts";
while true; do
    case "$1" in
        --no-load-balance)
            shift;
            no_load_balance=$1
            shift;
            ;;
        --rtprio)
            shift;
            # TODO: exit if not between 1-99
            rtprio_opt="--rtprio $1"
            shift;
            ;;
        --duration)
            shift;
            duration=$1
            shift;
            ;;
	--smt)
	    shift
	    smt=$1
	    shift
	    ;;	   
        --)
            shift;
            break
            ;;
        *)
            echo "Invalid option: $1"
            exit 1
    esac
done

if [ "$no_load_balance" == "1" ]; then
     disable_balance $cpus_list
fi

# adjust CPUs to use
cpu_str=""
for cpu in $(echo $WORKLOAD_CPUS | sed -e "s/,/ /g"); do
    cpu_str+=" --cpu $cpu"
done
cmd="${TOOLBOX_HOME}/bin/get-cpus-ordered.py --smt ${smt} ${cpu_str}"
echo "about to run: ${cmd}"
CMD_OUTPUT=$(${cmd})
echo -e "${CMD_OUTPUT}"
WORKLOAD_CPUS=$(echo -e "${CMD_OUTPUT}" | grep "final cpus:" | awk '{ print $3 }')
echo "WORLOAD_CPUS: ${WORKLOAD_CPUS}"

cpu_str=""
for cpu in $(echo $HK_CPUS | sed -e "s/,/ /g"); do
    cpu_str+=" --cpu $cpu"
done
cmd="${TOOLBOX_HOME}/bin/get-cpus-ordered.py --smt ${smt} ${cpu_str}"
echo "about to run: ${cmd}"
CMD_OUTPUT=$(${cmd})
echo -e "${CMD_OUTPUT}"
HK_CPUS=$(echo -e "${CMD_OUTPUT}" | grep "final cpus:" | awk '{ print $3 }')
echo "HK_CPUS: ${HK_CPUS}"

# get the first CPU from HK_CPUS to use as the oslat main thread
cpu_main_thread=$(echo ${HK_CPUS} | awk -F, '{ print $1 }')

echo
cmd="oslat --help"
echo "About to run: $cmd"
$cmd
echo
cmd="oslat --version"
echo "About to run: $cmd"
$cmd
echo

cmd="taskset -c ${HK_CPUS},${WORKLOAD_CPUS} oslat --duration ${duration} ${rtprio_opt} --cpu-list ${WORKLOAD_CPUS} --cpu-main-thread ${cpu_main_thread}"
echo "About to run: $cmd"
date +%s.%N >begin.txt
$cmd >oslat-bin-stderrout.txt 2>&1
rc=$?
date +%s.%N >end.txt

if [ "$no_load_balance" == "1" ]; then
     enable_balance $cpus_list
fi

if [ $rc -gt 0 ]; then
    exit_error "`cat oslat-bin-stderrout.txt`"
fi
