#!/bin/bash

if ! source ${TOOLBOX_HOME}/bash/library/bench-base; then echo "ERROR: Could not source bench-base from \$TOOLBOX_HOME [${TOOLBOX_HOME}]"; exit 1; fi

function disable_balance()
{
    local cpulist="$1"; shift
	local cpu=""
	local file=
	local flags_cur=
	for cpu in `echo ${cpulist} | sed -e 's/,/ /g'`; do
		for file in $(find /proc/sys/kernel/sched_domain/cpu$cpu -name flags -print); do
			flags_cur=$(cat $file)
			flags_cur=$((flags_cur & 0xfffe))
			echo $flags_cur > $file
		done
	done
}

function enable_balance()
{
    local cpulist="$1"; shift
	local cpu=""
	local file=
	local flags_cur=
	for cpu in `echo ${cpulist} | sed -e 's/,/ /g'`; do
		for file in $(find /proc/sys/kernel/sched_domain/cpu$cpu -name flags -print); do
			flags_cur=$(cat $file)
			flags_cur=$((flags_cur | 0x1))
			echo $flags_cur > $file
		done
	done
}

